[tool.poetry]
name = "pyselect"
version = "0.1.0"
description = "A package for embedding variable selection in machine learning algorithms."
license = "MIT"
readme = "README.md"
homepage = "https://github.com/mpotto/pyselect"
repository = "https://github.com/mpotto/pyselect"
keywords = []
authors = ["Mateus Otto <mateus.potto@usp.br>"]

[tool.poetry.dependencies]
python = "^3.7"
torch = "^1.8.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
