[tool.poetry]
name = "pyselect"
version = "0.1.0"
description = "A package for embedding variable selection in machine learning algorithms."
license = "MIT"
readme = "README.md"
homepage = "https://github.com/mpotto/pyselect"
repository = "https://github.com/mpotto/pyselect"
keywords = []
authors = ["Mateus Otto <mateus.potto@usp.br>"]

[tool.poetry.dependencies]
python = "^3.7"
torch = "^1.8.1"
ipykernel = "^5.5.5"
jupyter = "^1.0.0"
matplotlib = "^3.4.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
coverage = {extras = ["toml"], version = "^5.5"}
pytest-cov = "^2.12.0"
pytest-mock = "^3.6.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
